procedimento idade1 ( )  
    mostre "metodo1 "
fimprocedimento
procedimento idade2 ( )  
    mostre "metodo2 "
    mostre "call1 "
    idade1 ( )
fimprocedimento
procedimento idade3 ( )  
    mostre "call1 "
    idade1 ( )
    mostre "metodo3 "
    mostre "call2 "
    idade2 ( )
fimprocedimento
inicio
    mostre "ini1 "
    idade1 ( )
    mostre "ini3 "
    idade3 ( )
    escreva "Codigo inicio "
    // inteiro a
    // a <- 20 + a
fimalgoritmo

