funcao real pi ( )
escreva " pi "
retorne 3.14
fimfuncao
procedimento fazer1 ( inteiro a )
    escreva " \nhola 1- " , a
    escreva pi ( ) , " "
    escreva pi ( ) , " "
    escreva pi ( ) , " "
fimprocedimento
procedimento fazer2 ( inteiro a )
    escreva " \nhola 2- " , a
    escreva pi ( ) , " " , pi ( ) , " " , pi ( )
fimprocedimento
inicio
    escreva "Codigo principal \n"
    fazer1 ( 20 )
    escreva "\n"
    fazer2 ( 40 )
fimalgoritmo

