//ALGORITMO: "Coloque aqui o nome do algoritmo"
//AUTOR: "Augusto Bilabila"
//DATA: Wed Dec 21 22:59:35 GMT 2011
inicio
    literal a [ 4 ] <- {"inverno" , "outono" , "primavera" , "verão" }
    inteiro a1 <- 12
    escreva comprimento ( a [ 1 ] )
    literal nome1 <- "Linguagem"
    literal nome2 <- " Algoritmica"
    literal nome3 <- nome1 + nome2
    mostre ( "\n" + nome3 )
   // limpatela
    mostre "Pompou"
fimalgoritmo

