/*ALGORITMO: Genero_1
--AUTOR: Bilabila
--DATA: Mon Jan 16 05:41:25 GMT 2012*/
inicio
    caracter sexo
    escreva "Qual o seu género (M ou F)? :"
    leia ( sexo )
    escreva "Olá "
    escolha sexo
        caso "M" :
            escreva "Homem"
        caso "F" :
            escreva "Mulher"
        defeito :
            escreva "Sexo indefinido"
    fimescolha
    escreva " , bemvindo CompAlg"
fimalgoritmo


